
###登录
POST http://localhost:8081/api/auth/login
Content-Type: application/json

    {
    "username": "admin",
    "password": "admin"
    }


###
POST http://localhost:8081/api/auth/logout
Content-Type: application/json
Authorization: Bearer <REPLACE_WITH_JWT>

{
  "access-token" : "<REPLACE_WITH_JWT>"
}
